# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_dinner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='host',
        ),
        migrations.AddField(
            model_name='host',
            name='students',
            field=models.ManyToManyField(to='thanksgiving_dinner.Student'),
        ),
    ]
