# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-28 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_dinner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='interest',
            table='interest',
        ),
    ]
