# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_dinner', '0003_auto_20171025_0525'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='host',
        ),
    ]
