# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_dinner', '0004_auto_20171025_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date',
        ),
    ]
