# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thanksgiving_dinner', '0005_auto_20171025_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
